### ISSUE TITLE
开启混淆后crash

### ISSUE THREAD

**Issue by xiaotian-freedom** [aleyn97/MVVMLin#24]
Caused by: java.lang.NoSuchMethodException: zy.inflate [class android.view.LayoutInflater]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.commonlib.base.BaseActivity$a.a(BaseActivity.kt:3)
        at com.commonlib.base.BaseActivity$a.invoke(BaseActivity.kt:1)
        at yj2.getValue(LazyJVM.kt:5)
        at com.commonlib.base.BaseActivity.d(Unknown Source:2)
        at com.commonlib.base.BaseActivity.h(BaseActivity.kt:1)
        at com.commonlib.base.BaseActivity.onCreate(BaseActivity.kt:3)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)

**Comment by aleyn97** [comment]
dev 分支有混淆规则，添加一下
